# Generated by Django 3.0.8 on 2020-07-09 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('show_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=10000)),
                ('name', models.CharField(max_length=10000)),
                ('name_url', models.ImageField(upload_to='image')),
                ('type', models.CharField(max_length=10000)),
                ('fans', models.CharField(max_length=10000)),
                ('popularity', models.CharField(max_length=10000)),
                ('time', models.DateTimeField(auto_now=True)),
                ('dizhi', models.CharField(max_length=10000)),
            ],
        ),
    ]
